apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-mongodb-pv
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: localstorage
  hostPath:
    path: /tmp/mongodb/
